### ISSUE TITLE
Context view is undefined

### ISSUE THREAD

**Issue by mistrett** [janl/mustache.js#718]
I use mustache in a nodejs application as dependency of mustache-express.

I get this error:
```
.../node_modules/mustache/mustache.js:448
          intermediateValue = context.view[name];
                                          ^

TypeError: Cannot read property 'title' of undefined
    at Context.lookup (...\node_modules\mustache\mustache.js:448:43)
    at Writer.renderSection (...\node_modules\mustache\mustache.js:575:25)
    at Writer.renderTokens (...\node_modules\mustache\mustache.js:558:40)
    at Writer.renderSection (...\node_modules\mustache\mustache.js:587:24)
    at Writer.renderTokens (...\node_modules\mustache\mustache.js:558:40)
    at Writer.renderSection (...\node_modules\mustache\mustache.js:601:22)
    at Writer.renderTokens (...\node_modules\mustache\mustache.js:558:40)
    at Writer.renderPartial (...\node_modules\mustache\mustache.js:638:19)
    at Writer.renderTokens (...\node_modules\mustache\mustache.js:560:45)
    at Writer.renderInverted (...\node_modules\mustache\mustache.js:612:19)

```

My template code that generate this issue is:

```
{{#hasClusters}}
  <div class="row servicesRow my-5">
    <div class="col">
      <div class="section-title">SERVIZI E DETTAGLI</div>
      <div class="plain-clusters collapse hidden fit">
        {{#clusters}}
          {{#title}} {{! <- THIS IS THE PROPERTY THAT GENERATE THE ERROR}}
            <p>{{title}}</p>
            <ul class="list-unstyled">
              {{#items}}
                <li>{{value}}</li>
              {{/items}}
            </ul>
          {{/title}}
        {{/clusters}}
      </div>
    </div>
  </div>
{{/hasClusters}}
```
I have sure that the input JSON contains the 'clusers' array with n objects with 'title' attribute.

To solve the issue I found a workaround: i have replaced {{#clusters}} with {{#clusters}}{{#.}} ... {{/.}}{{/clusters}} this change the mustache context and solve the issue.

However, before I try to solve this issue in mustache (mustache.js); I change the following 'else'
```
	if (name.indexOf('.') > 0) {
         ...
        } else {
          intermediateValue = context.view[name]; // <-- ERROR IS THROW HERE!!!!

          /**
           * Only checking against `hasProperty`, which always returns `false` if
           * `context.view` is not an object. Deliberately omitting the check
           * against `primitiveHasOwnProperty` if dot notation is not used.
           *
           * Consider this example:
           * ```
           * Mustache.render("The length of a football field is {{#length}}{{length}}{{/length}}.", {length: "100 yards"})
           * ```
           *
           * If we were to check also against `primitiveHasOwnProperty`, as we do
           * in the dot notation case, then render call would return:
           *
           * "The length of a football field is 9."
           *
           * rather than the expected:
           *
           * "The length of a football field is 100 yards."
           **/
          lookupHit = hasProperty(context.view, name);
        }

	if (lookupHit) {
          value = intermediateValue;
          break;
        }

        context = context.parent;
```
with
```
else if(context.view!==undefined)  {...}
```
With this condition the lookup fails (lookupHit is false) and at the next iteration context.view['title'] is the correct title.

I've used the second solution only for understand how i can solve the issue into my code, and I not really sure that it's a good solution.

I hope that my explanation is adequate to help you to solve this issue.

Antonino

**Comment by mistrett** [comment]
I found the cause of the given error. The 'customers' array has a wrong length because of a delete operation of an array item. I've replaced delete with a slice and the error is fixed.

Antonino

**Comment by phillipj** [comment]
Cool, good to hear you found the culprit and remembered to close this issue 👍
